# Generated by Django 4.0.3 on 2022-04-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_comment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(default='Type Here', max_length=300),
        ),
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.TextField(default='Add Title', max_length=100),
        ),
    ]
