# Generated by Django 4.0.3 on 2022-04-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='galleries',
            field=models.ManyToManyField(to='main_app.gallery'),
        ),
    ]
